#!/usr/bin/env bash
#
# uguush - command-line uploader for uguu.se and others
#

## CONFIGURATION

# colors
c0="$(tput sgr0)"
c1="$(tput setaf 1)"
c2="$(tput setaf 2)"

# screenshot functions
capFullscreen() {
	if [ "${useSpectacle}" = 'true' ]; then
		spectacle -bno "${localFile}"
	else
		maim -u "${localFile}"
	fi
}

capSelection() {
	if [ "${useSpectacle}" = 'true' ]; then
		if [ -n "$(spectacle -rbno "${localFile}" 2>&1)" ]; then
			delTemp
		fi
	else
		maim -su "${localFile}" || delTemp
	fi
}

capWindow() {
	if [ "${useSpectacle}" = 'true' ]; then
		spectacle -abno "${localFile}"
	elif [ "${doWindowShadow}" = 'true' ]; then
		maim -u -i $(xdotool getactivewindow) |
		convert - \( +clone -background black -shadow 60x30+0+0 \) +swap -background none -layers merge +repage "${localFile}"
	else
		maim -u -i $(xdotool getactivewindow) "${localFile}"
	fi
}

# delay
delaySeconds='0'

# hosts and shorteners
host='fiery'
shortener=
hosts='uguu teknik 0x0 ptpb mixtape lewd fiery doko'
shorteners='waaai 0x0'

## FUNCTIONS

depends() {
	if [ ! type curl &> /dev/null ]; then
		echo >&2 "Checking for curl... [${c1}FAILED${c0}]"
		echo 'curl not found.'
		exit 1
	fi
}

usage() {
	cat << EOF

uguush - upload to various file hosts

Usage:
	$(basename "${0}") [options]

Options:
	-d		Delay the screenshot by the specified number of seconds.
	-f		Take a fullscreen screenshot.
	-h		Show this help message.
	-o		Select a host to use. Can be uguu, teknik, 0x0, ptpb, mixtape, lewd, fiery or doko.
	-p <path>	Custom path to save the image to. Saves the image as "%Y-%m-%d %H-%M-%S.png".
	-n		Enable save notification (if used alongside -p option).
	-s		Take a selection screenshot.
	-u <file>	Upload a file.
	-x		Do not notify dbus, update the log, or modify the clipboard.
	-w		Take a screenshot of the current window.
	-S		Select a shortener to use. Can be waaai or 0x0.
	-i		Apply shadow effect to window screenshot using ImageMagick.
	-l <url>	Upload the file at the provided URL.
	-k		Use Spectacle of KDE Plasma (with -p file name will be "Screenshot_%Y%m%d_%H%M%S.png").
	-t <token>	Set token (only for fiery host).
	-a <id>		Set numerical ID of an album (only for fiery host).

EOF
}

delay() {
	for (( i=delaySeconds; i > 0; --i )); do
		echo "${i}..."
		sleep 1
	done
}

screenshot() {
	if [ "${doFullscreen}" = 'true' ]; then
		capFullscreen
	elif [ "${doSelection}" = 'true' ]; then
		capSelection
	elif [ "${doWindow}" = 'true' ]; then
		capWindow
	elif [ "${doURL}" = 'true' ]; then
		if [ -f "/usr/share/mime/globs" ]; then
			urlExtension="$(curl -sf --head "${remoteURL}" | grep 'Content-Type: ' | head -1 | grep -Po '(?<=\ )[^\;]*')"
			urlExtension="$(echo "${urlExtension}" | sed -e "s/\\r//")"
			urlExtension="$(cat /usr/share/mime/globs | grep "${urlExtension}" | sort -r | head -1 | grep -Po '(?<=\.)[^\n]*')"
		else
			urlExtension="$(basename ${remoteURL})"
			urlExtension=${urlExtension#*.}
		fi
		localFile="${localTemp}.${urlExtension}"
		$(curl -sf "${remoteURL}" > "${localFile}")
	fi

	if [ "${notifySave}" = 'true' ] && [ "${saveToPath}" = 'true' ]; then
		notify-send "uguu~" "A screenshot was saved as '${dateFilename}' to '${pathToSave}'" -h string:x-canonical-private-synchronous:uguush -i document-save
	fi
}

upload() {
	for (( i = 1; i <= 3; i++ )); do
		echo -n "Try #${i}... "

		case "${host}" in
			teknik) hostURL='https://api.teknik.io/v1/Upload' ;;
			0x0) hostURL='https://0x0.st/' ;;
			uguu) hostURL='https://uguu.se/api.php?d=upload-tool' ;;
			ptpb) hostURL='https://ptpb.pw/' ;;
			mixtape) hostURL='https://mixtape.moe/upload.php' ;;
			lewd) hostURL='https://lewd.se/api.php?d=upload-tool' ;;
			fiery) hostURL='https://safe.fiery.me/api/upload' ;;
			doko) hostURL='https://doko.moe/upload.php' ;;
		esac

		case "${shortener}" in
			waaai) shortenerURL='https://api.waa.ai/shorten' ;;
			0x0) shortenerURL='http://0x0.st/' ;;
			ptpb) shortenerURL='https://ptpb.pw/u' ;;
		esac

		if [ "${host}" = 'uguu' ]; then
			uploadResult="$(curl -sf -F file="@${localFile}" "${hostURL}")"
		elif [ "${host}" = '0x0' ]; then
			uploadResult="$(curl -sf -F file="@${localFile}" "${hostURL}")"
		elif [ "${host}" = 'teknik' ]; then
			uploadResult="$(curl -sf -F file="@${localFile}" "${hostURL}")"
			uploadResult="${uploadResult##*url\":\"}"
			uploadResult="${uploadResult%%\"*}"
		elif [ "${host}" = 'mixtape' ]; then
			uploadResult="$(curl -sf -F files[]="@${localFile}" "${hostURL}")"
			uploadResult="$(echo "${uploadResult}" | grep -Po '"url":"[A-Za-z0-9]+.*?"' | sed 's/"url":"//;s/"//')"
			uploadResult="$(echo "${uploadResult//\\\//\/}")"
		elif [ "${host}" = 'ptpb' ]; then
			uploadResult="$(curl -sf -F c="@${localFile}" "${hostURL}")"
			uploadResult="${uploadResult##*url: }"
			uploadResult="${uploadResult%%$'\n'*}"
		elif [ "${host}" = 'lewd' ]; then
			uploadResult="$(curl -sf -F file="@${localFile}" "${hostURL}")"
		elif [ "${host}" = 'fiery' ]; then
			uploadResult="$(curl -H "token: ${fieryToken}" -H "albumid: ${fieryAlbumId}" -sf -F files[]="@${localFile}" "${hostURL}")"
			uploadResult="$(echo "${uploadResult}" | grep -Po '"url":"[A-Za-z0-9]+.*?"' | sed 's/"url":"//;s/"//')"
		elif [ "${host}" = 'doko' ]; then
			uploadResult="$(curl -sf -F files[]="@${localFile}" "${hostURL}")"
			uploadResult="$(echo "${uploadResult}" | grep -Po '"url":"[A-Za-z0-9]+.*?"' | sed 's/"url":"//;s/"//')"
			uploadResult="$(echo "${uploadResult//\\\//\/}")"
		fi

		if [ "${shortener}" = 'waaai' ]; then
			tempResult="$(curl -sf -F url="${uploadResult}" "${shortenerURL}")"
			shortCode="${tempResult##*short_code\":\"}"
			shortCode="${shortCode%%\"*}"
			shortenerResult="https://waa.ai/${shortCode}"
			shortenerExtension="${tempResult##*extension\":}"
			shortenerExtension="${shortenerExtension%%\}*}"
			if [ "${shortenerExtension}" = 'true' ]; then
				shortenerExtension=${shortenerExtension##\"}
				shortenerExtension=${shortenerExtension%%\"}
				shortenerResult="${shortenerResult}.${shortenerExtension}"
			fi
		elif [ "${shortener}" = '0x0' ]; then
			shortenerResult="$(curl -sf -F shorten="${uploadResult}" "${shortenerURL}")"
		elif [ "${shortener}" = 'ptpb' ]; then
			shortenerResult="$(curl -sf -F c=@- "${shortenerURL}" <<< "${uploadResult}")"
		fi

		if [ "${shortener}" ]; then
			finalResult="${shortenerResult}"
		else
			finalResult="${uploadResult}"
		fi

		if [ "${?}" = 0 ]; then

			# copy to clipboard, log, and notify (unless $noComms is set)
			if [ ! "${noComms}" ]; then
					echo -n "${finalResult}" | xclip -selection primary
					echo -n "${finalResult}" | xclip -selection clipboard
					echo "$(date +"%D %R") | "${file}" | "${finalResult}"" >> ~/.uguush.log
					notify-send "uguu~" "Link copied to clipboard: '${finalResult}'" -h string:x-canonical-private-synchronous:uguush -i up
			fi
		fi

		echo "[${c2}OK${c0}]"
		echo "File has been uploaded: ${finalResult}"

		# if we took a screenshot, remove the temporary file
		if [ -z "${doFile}" ] && [ -z "${saveToPath}" ]; then
			rm "${localFile}"
		fi

		exit

	done
}

path() {
	if [ "${saveToPath}" = 'true' ]; then
		if [ "${useSpectacle}" = 'true' ]; then
			# this is Spectacle's default naming format
			dateFilename="$(date '+Screenshot_%Y%m%d_%H%M%S').png";
		else
			dateFilename="$(date '+%Y-%m-%d %H-%M-%S').png";
		fi
		localFile="${pathToSave}/${dateFilename}"
	else
		# filename to use for screenshots
		localTemp="$(mktemp)"
		localFile="${localTemp}.png"
		mv "${localTemp}" "${localFile}"
	fi
}

delTemp() {
	if [ -f "${localFile}" ]; then
		rm "${localFile}"
	fi
	exit 1
}

## PARSE OPTIONS

while getopts :a:d:fhikl:no:p:st:u:wxS: opt ;do
	case "${opt}" in
		a)
			# set fiery album id
			fieryAlbumId="${OPTARG}" ;;
		d)
			# set delay value
			delaySeconds="${OPTARG}" ;;
		f)
			# take fullscreen shot
			doFullscreen='true' ;;
		h)
			# print help
			usage
			exit 0 ;;
		i)
			# add shadow effect using ImageMagick
			doWindowShadow='true' ;;
		k)
			# use Spectacle of KDE Plasma
			useSpectacle='true' ;;
		l)
			# set url to upload
			doURL='true'
			remoteURL="${OPTARG}" ;;
		n)
			# enable save notification
			notifySave='true' ;;
		o)
			# set host
			[[ "${hosts}" =~ "${OPTARG}" ]] && host="${OPTARG}" || exit 1 ;;
		p)
			# set path to save file
			saveToPath='true'
			pathToSave="${OPTARG}" ;;
		s)
			# take shot of selection
			doSelection='true' ;;
		t)
			# use fiery token
			fieryToken="${OPTARG}" ;;
		u)
			# change $file to the specified file with -u
			doFile='true'
			localFile="${OPTARG}" ;;
		w)
			# take shot of current window
			doWindow='true' ;;
		x)
			# do not notify dbus, update log, or modify clipboard
			noComms='true' ;;
		S)
			# set shortener
			[[ "${shorteners}" =~ "${OPTARG}" ]] && shortener="${OPTARG}" || exit 1 ;;
		*)
			# print help and EXIT_FAILURE
			usage
			exit 1 ;;
	esac
done

# show usage if no arguments are given
if [ $# -lt 1 ]; then
	usage
	exit 1
fi

## EXECUTE FUNCTIONS

depends
delay
path
screenshot
upload

# if the program doesn't exit at the for-loop, the upload failed
echo 'File was not uploaded, did you specify a valid filename?'
